--- #YAML:1.0
name:               Net-SSH2
version:            0.19
abstract:           Support for the SSH 2 protocol via libssh2.
author:
    - David B. Robins <dbrobins@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:  0
    IO::File:        0
    Socket:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
